{% set version = "3.7.7.1" %}

package:
  name: ephem
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/ephem/ephem-{{ version }}.tar.gz
  sha256: 36b51a8dc7cfdeb456dd6b8ab811accab8341b2d562ee3c6f4c86f6d3dbb984e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - ephem
    - ephem._libastro

about:
  home: http://rhodesmill.org/pyephem/
  license: LGPL
  license_file: COPYING
  summary: Basic astronomical computations for Python
  description: |
    PyEphem provides an ``ephem`` Python package for performing high-precision
    astronomy computations. The underlying numeric routines are coded in C and
    are the same ones that drive the popular `XEphem`_ astronomy application,
    whose author, Elwood Charles Downey, generously gave permission for their
    use in PyEphem. The name *ephem* is short for the word *ephemeris*, which
    is the traditional term for a table giving the position of a planet,
    asteroid, or comet for a series of dates. The design of PyEphem emphasizes
    convenience and ease of use. Both celestial bodies and the observer's
    location on Earth are represented by Python objects, while dates and
    angles automatically print themselves in standard astronomical formats.
  doc_url: http://rhodesmill.org/pyephem/
  dev_url: https://github.com/brandon-rhodes/pyephem

extra:
  recipe-maintainers:
    - bsipocz
    - mwcraig
    - tacaswell
    - ocefpaf
